# Generated by Django 5.2.7 on 2026-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecret',
            name='verification_otp_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='Código de verificación (Cifrado)'),
        ),
        migrations.AddField(
            model_name='usersecret',
            name='verification_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Código de verificación expira el'),
        ),
    ]
