# Generated by Django 5.2.7 on 2026-01-14 10:17

import apps.users.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255, verbose_name='Dirección (Calle y número)')),
                ('address_line_2', models.CharField(blank=True, help_text='Apartamento, unidad, edificio, piso, etc.', max_length=255, null=True, verbose_name='Dirección (Línea 2)')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('state_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado / Provincia')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Dirección de correo electrónico')),
                ('username', models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre.'}, help_text='Requerido. 150 caracteres o menos. Letras, dígitos y @/./+/-/_ solamente.', max_length=150, unique=True, verbose_name='Nombre de usuario')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP de conexión')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Último cambio de contraseña')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos de login fallidos')),
                ('is_anonymized', models.BooleanField(default=False, verbose_name='Anonimizado')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de borrado')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si el usuario ha confirmado su dirección de correo.', verbose_name='Email verificado')),
                ('is_suspended', models.BooleanField(default=False, help_text='Indica si la cuenta ha sido suspendida administrativamente.', verbose_name='Suspendido')),
                ('suspension_reason', models.TextField(blank=True, null=True, verbose_name='Razón de suspensión')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_billing', to='users.address', verbose_name='Dirección de facturación')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_shipping', to='users.address', verbose_name='Dirección de envío')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', apps.users.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=100, verbose_name='Zona Horaria')),
                ('preferred_currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda Preferida')),
                ('language_code', models.CharField(default='en-us', max_length=10, verbose_name='Idioma')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('role', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('admin', 'Admin')], default='free', max_length=50, verbose_name='Rol')),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('accepted_terms_at', models.DateTimeField(blank=True, null=True, verbose_name='Términos aceptados el')),
                ('accepted_privacy_policy_at', models.DateTimeField(blank=True, null=True, verbose_name='Privacidad aceptada el')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Consentimiento de marketing')),
                ('registration_data', models.JSONField(blank=True, default=dict, verbose_name='Datos de registro')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Última actividad')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de borrado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='UserSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_encrypted', models.TextField(blank=True, null=True, verbose_name='DNI / NIF (Cifrado)')),
                ('dni_index', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='DNI / NIF (Índice)')),
                ('date_of_birth_encrypted', models.TextField(blank=True, null=True, verbose_name='Fecha de nacimiento (Cifrado)')),
                ('phone_number_encrypted', models.TextField(blank=True, null=True, verbose_name='Teléfono (Cifrado)')),
                ('phone_number_index', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Teléfono (Índice)')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Teléfono verificado el')),
                ('api_key_binance_encrypted', models.TextField(blank=True, null=True, verbose_name='Binance API Key (Cifrada)')),
                ('api_key_binance_index', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Binance API Key (Índice)')),
                ('api_secret_binance_encrypted', models.TextField(blank=True, null=True, verbose_name='Binance API Secret (Cifrada)')),
                ('otp_secret_key', models.CharField(blank=True, help_text='Semilla TOTP (Cifrada)', max_length=255, null=True, verbose_name='Clave secreta 2FA')),
                ('otp_recovery_codes', models.TextField(blank=True, help_text='Códigos de respaldo (Cifrados)', null=True, verbose_name='Códigos de recuperación 2FA')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de borrado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Secretos de Usuario',
                'verbose_name_plural': 'Secretos de Usuarios',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
    ]
