# Generated by Django 5.2.7 on 2026-03-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('admin', 'Admin')], default='free', max_length=15, verbose_name='Rol de usuario'),
        ),
    ]
