# Generated by Django 5.2.7 on 2026-03-29 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_two_factor_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="usersecret",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                help_text="Apartment, unit, building, floor, etc.",
                max_length=255,
                null=True,
                verbose_name="Address line 2",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=20, verbose_name="Postal code"),
        ),
        migrations.AlterField(
            model_name="address",
            name="state_province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="State / Province"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_address",
            field=models.CharField(max_length=255, verbose_name="Street address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_billing",
                to="users.address",
                verbose_name="Billing address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Failed login attempts"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_anonymized",
            field=models.BooleanField(default=False, verbose_name="Is anonymized"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_suspended",
            field=models.BooleanField(default=False, verbose_name="Is suspended"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Email verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Last IP address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last password change"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_shipping",
                to="users.address",
                verbose_name="Shipping address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="suspension_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Suspension reason"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer.",
                max_length=150,
                unique=True,
                verbose_name="Username",
            ),
        ),
        migrations.CreateModel(
            name="UserSecretAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_affected",
                    models.CharField(max_length=50, verbose_name="Campo afectado"),
                ),
                (
                    "action_type",
                    models.CharField(max_length=10, verbose_name="Tipo de acción"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP del cambio"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría de Secrecto",
                "verbose_name_plural": "Auditorías de Secrectos",
                "ordering": ["-timestamp"],
            },
        ),
    ]
