# Generated by Django 5.2.7 on 2026-07-30 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersecret_verification_otp_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersecret',
            options={'verbose_name': 'User secret', 'verbose_name_plural': 'User secrets'},
        ),
        migrations.AlterModelOptions(
            name='usersecretaudit',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Secret audit entry', 'verbose_name_plural': 'Secret audit entries'},
        ),
        migrations.RemoveField(
            model_name='usersecret',
            name='api_key_binance_encrypted',
        ),
        migrations.RemoveField(
            model_name='usersecret',
            name='api_key_binance_index',
        ),
        migrations.RemoveField(
            model_name='usersecret',
            name='api_secret_binance_encrypted',
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='date_of_birth_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='Date of birth (encrypted)'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='dni_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='National ID (encrypted)'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='dni_index',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='National ID (blind index)'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='otp_recovery_codes',
            field=models.TextField(blank=True, null=True, verbose_name='2FA recovery codes'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='otp_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2FA secret key'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='phone_number_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='Phone number (encrypted)'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='phone_number_index',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Phone number (blind index)'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phone verified at'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='verification_otp_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='Verification code (encrypted)'),
        ),
        migrations.AlterField(
            model_name='usersecret',
            name='verification_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification code expires at'),
        ),
        migrations.AlterField(
            model_name='usersecretaudit',
            name='action_type',
            field=models.CharField(max_length=10, verbose_name='Action type'),
        ),
        migrations.AlterField(
            model_name='usersecretaudit',
            name='field_affected',
            field=models.CharField(max_length=50, verbose_name='Field affected'),
        ),
        migrations.AlterField(
            model_name='usersecretaudit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP'),
        ),
        migrations.AlterField(
            model_name='usersecretaudit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='usersecretaudit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_audits', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
