# Generated by Django 5.2.7 on 2026-07-30 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usersecret_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accepted_privacy_policy_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Privacy policy accepted at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terms accepted at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Email notifications enabled'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language_code',
            field=models.CharField(default='en-us', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last activity at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Marketing consent'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(default='USD', max_length=10, verbose_name='Preferred currency'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registration_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Registration metadata'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('admin', 'Admin')], default='free', max_length=15, verbose_name='User role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100, verbose_name='Time zone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
